# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  HipPitch:
    has_velocity_limits: true
    max_velocity: 2.93276
    has_acceleration_limits: false
    max_acceleration: 0
  HipRoll:
    has_velocity_limits: true
    max_velocity: 2.27032
    has_acceleration_limits: false
    max_acceleration: 0
  KneePitch:
    has_velocity_limits: true
    max_velocity: 2.93276
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowYaw:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  LHand:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderPitch:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  LWristYaw:
    has_velocity_limits: true
    max_velocity: 17.3835
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowYaw:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  RHand:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderPitch:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  RWristYaw:
    has_velocity_limits: true
    max_velocity: 17.3835
    has_acceleration_limits: false
    max_acceleration: 0